x-env-file: &env_file
  - .env

name: yarr

services:
  yarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yarr
    image: yarr:latest
    ports:
      - "7070:7070"
    restart: unless-stopped
    env_file: *env_file
